# Generated by Django 4.1.1 on 2022-10-04 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20220826_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='The ISBN of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='Date the book was published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='The title of the book', max_length=70),
        ),
        migrations.AlterField(
            model_name='bookcontributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co_Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role the contributor had in the book'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(help_text='The contact email of the contributor', max_length=254),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(help_text="The contributor's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(help_text="The contributor's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(help_text='The contact email of the publisher', max_length=254),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='The name of the publisher', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(help_text='The website of the publisher'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(help_text='The book that this review is for', on_delete=django.db.models.deletion.CASCADE, to='reviews.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='The review comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(help_text='The creator of the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='The date and time the review was last edited', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='The rating the reviewer has given'),
        ),
    ]
